version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-scripts.sql:/docker-entrypoint-initdb.d/init-user.sql

  backend:
    container_name: backend
    image: portal-server:v1.0.1
    ports:
      - "5000:5000"
    env_file:
      - ./server/.deployment/.env.dev
    depends_on:
      - postgres
      - redis

  frontend:
    container_name: frontend
    image: portal-client:v1.0.1
    ports:
      - "3001:3001"
    env_file:
      - ./client/.deployment/.env.dev
    depends_on:
      - backend

volumes:
  pg_data:
